### ISSUE TITLE
Error when training text-line detection model

### ISSUE THREAD

**Issue by huyhoang17** [JiaquanYe/TableMASTER-mmocr#11]
Hi, thanks for the great repo!

- I followed the guide in the README file and want to train the text-line detection model
- I also prepared a dataset with COCO format, same as the MMOCR's repo and [psenet_r50_fpnf_600e_pubtabnet.py](https://github.com/JiaquanYe/TableMASTER-mmocr/blob/master/configs/textdet/psenet/psenet_r50_fpnf_600e_pubtabnet.py) but got the following error. Seem like it occurs with an empty object but I did not sure the error came from
Did you face this issue when training the text-line detection model? Or do you have an idea about how to fix this issue?

Thanks in advance!

![photo6170031322173648295](https://user-images.githubusercontent.com/15128654/132119864-3acc56f6-3b46-4330-8e16-3e1ca476f144.jpg)

**Comment by JiaquanYe** [comment]
> Hi, thanks for the great repo!
> 
> * I followed the guide in the README file and want to train the text-line detection model
> * I also prepared a dataset with COCO format, same as the MMOCR's repo and [psenet_r50_fpnf_600e_pubtabnet.py](https://github.com/JiaquanYe/TableMASTER-mmocr/blob/master/configs/textdet/psenet/psenet_r50_fpnf_600e_pubtabnet.py) but got the following error. Seem like it occurs with an empty object but I did not sure the error came from
>   Did you face this issue when training the text-line detection model? Or do you have an idea about how to fix this issue?
> 
> Thanks in advance!
> 
> ![photo6170031322173648295](https://user-images.githubusercontent.com/15128654/132119864-3acc56f6-3b46-4330-8e16-3e1ca476f144.jpg)

Hi, seem like it is failed to load the training data. And what's your MMDet version?
Maybe you can check the data loading setting in config file, or check the data loading pipeline.

**Comment by JiaquanYe** [comment]
Hi, seem like it is failed to load the training data. And what's your MMDet version?
Maybe you can check the data loading setting in config file, or check the data loading pipeline.

**Comment by huyhoang17** [comment]
@JiaquanYe 
lib version
```bash
mmocr: 0.2.0 (installed from repo)
mmdet: 2.11.0 (installed from repo)
mmcv-full: 1.3.4
```

I checked and just realized that when training the model, it's called the `build_dataset` function first to building the dataset. But I searched through all the source code and only find this function from mmdet? Is it normal?

Here is my PSE config: https://pikab.in/5127bb5d68
`train.json` is under COCO format, `images` is the folder contains the image data

**Comment by huyhoang17** [comment]
@JiaquanYe 
Can you provide the pre-trained PSENet text-line detection model?
Currently, I want to test the pipeline but can not train the text-line detection due to this issue. 
Hope to see your response, thank you!

**Comment by JiaquanYe** [comment]
> @JiaquanYe
> lib version
> 
> ```shell
> mmocr: 0.2.0 (installed from this repo)
> mmdet: 2.11.0 (installed from this repo)
> mmcv-full: 1.3.4
> ```
> 
> I checked and just realized that when training the model, it's called the `build_dataset` function first to building the dataset. But I searched through all the source code and only find this function from mmdet? Is it normal?
> 
> Here is my PSE config: https://pikab.in/5127bb5d68
> `train.json` is under COCO format, `images` is the folder contains the image data

Could you paste your train.json here?

**Comment by huyhoang17** [comment]
@JiaquanYe Here is the example of json file: https://pikab.in/537fbc4566

**Comment by huyhoang17** [comment]
I found the error. Must set the name of the category to `text` and turn on `with_mask=True` in the config file
Closed. Thank you for your support!
