### ISSUE TITLE
structure recognition accuracy is ~0.78，teds score is ~0.967，why？Is it reasonable？

### ISSUE THREAD

**Issue by smartshuhui** [JiaquanYe/TableMASTER-mmocr#12]

**Comment by JiaquanYe** [comment]
0.78 is structure recognition word accuracy. TEDS is metric measures both the structure similarity and the cell content similarity between the prediction and the ground truth. You find the details is this [repo](https://github.com/ibm-aur-nlp/PubTabNet/tree/master/src)

**Comment by smartshuhui** [comment]
@JiaquanYe Ok, i get it, 0.78 is  _**word**_  acc, it seems more reasonable. Thanks!

**Comment by delveintodetail** [comment]
> @JiaquanYe Ok, i get it, 0.78 is _**word**_ acc, it seems more reasonable. Thanks!

Yes, it seems reasonable. You can get a slightly better result via model ensemble.
