### ISSUE TITLE
Convert model to ONNX / TensorRT?

### ISSUE THREAD

**Issue by huyhoang17** [JiaquanYe/TableMASTER-mmocr#13]
Have you tried to convert the MASTER-based model (included textline-recognition & table recognition) to ONNX or TensorRT format?

I followed the tutorial of MMOCR and MMDet to convert those models to ONNX format, here is the output error
Do you have any idea for handle this issue? Thanks in advance.

![image](https://user-images.githubusercontent.com/15128654/132981552-b44ead7b-8aee-4393-89e3-2c710c2f4e73.png)

**Comment by delveintodetail** [comment]
我们没有干这个事， 我们其他的项目里面转过， 但是对一个表格识别，我们没有做这个。。。

**Comment by huyhoang17** [comment]
Closed. I can convert those models to torchserve format

**Comment by pjw-cmd** [comment]
> 
I also had problems converting onnx models.How did you convert the model to torchserve format?

**Comment by pjw-cmd** [comment]
> Closed. I can convert those models to torchserve format
I also had problems converting onnx models.How did you convert the model to torchserve format?
