### ISSUE TITLE
Master is not registy，是需要单独用master训练？

### ISSUE THREAD

**Issue by cqray1990** [JiaquanYe/TableMASTER-mmocr#29]
return build_from_cfg(cfg, registry, default_args)
  File "/python3.6/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'MASTER is not in the detector registry'

**Comment by JiaquanYe** [comment]
> ```
> return build_from_cfg(cfg, registry, default_args)
> ```
> 
> File "/python3.6/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg f'{obj_type} is not in the {registry.name} registry') KeyError: 'MASTER is not in the detector registry'

It seems like that you do not install mmocr package by run 'pip install -v -e .' in this repo's mmocr folder.
We also recommend you to use the docker enrivonment by run 'docker pull jiaquanye/tablemaster_mmocr:v1'

**Comment by cqray1990** [comment]
i get it
