### ISSUE TITLE
请问利用开源预训练模型与测试接口识别测试集的图片出现如贴图样式的内容乱码是什么原因？

### ISSUE THREAD

**Issue by peng06051126** [JiaquanYe/TableMASTER-mmocr#36]
输入
![image](https://user-images.githubusercontent.com/51046864/146113498-8e9770bf-b949-4d5a-978e-a44a65de08b5.png)

输出
![image](https://user-images.githubusercontent.com/51046864/146113578-39ad30ee-57c1-458c-a3e1-9ff7e9a1d82a.png)

**Comment by JiaquanYe** [comment]
May use a wrong alphabet...
We have released the alphabet of MASTER pretrain model at [here](https://github.com/JiaquanYe/TableMASTER-mmocr/tree/master/table_recognition/demo/alphabet)

**Comment by ttm43** [comment]
请问你是如何将输出的html代码转换为图片的呢？
