### ISSUE TITLE
missing text line recognition alphabet

### ISSUE THREAD

**Issue by zezeze97** [JiaquanYe/TableMASTER-mmocr#39]
Hi, thanks for publishing code. when I try to use text recognition checkpoint, find that the alphabet generated by mine is different from yours. This could be due to the fact that I only used part of the data for training master test recongnition model.  Could you provide the ./tools/data/alphabet/textline_recognition_alphabet.txt file?

**Comment by tomatoccnn** [comment]
你好，请问你解决这个问题了吗？我也找不到这个文件

**Comment by zezeze97** [comment]
TableMASTER-mmocr/table_recognition/demo/alphabet/
