### ISSUE TITLE
缺少 textline_recognition_alphabet.txt 文件

### ISSUE THREAD

**Issue by fly8764** [JiaquanYe/TableMASTER-mmocr#40]
No such file or directory: './tools/data/alphabet/textline_recognition_alphabet.txt'，仓库中没有提供这个文件。
在运行table_recognition.py文件时，遇到这个问题。

**Comment by fly8764** [comment]
第二个问题：No such file or directory: '/tmp/tmp8jizkmiu/tmpqe7zf89w.py'

**Comment by fly8764** [comment]
在 table_recognition/demo/alphabet/textline_recognition_alphabet.txt 路径中。

**Comment by ttm43** [comment]
你好，请问你是如何解决的？

**Comment by pjw-cmd** [comment]
I also encountered the same problem. How did you solve it.
