### ISSUE TITLE
keyError:'TABLEMASTER is not in the {registry.name} registry'

### ISSUE THREAD

**Issue by BrandnewA** [JiaquanYe/TableMASTER-mmocr#9]
您好，按照Install.md安装了mmdetection、mmcv-full、mmocr，
但是运行 sh ./table_recognition/expr/table_recognition_dist_train.sh 报错：
keyError:'TABLEMASTER is not in the {registry.name} registry'，
请问有什么建议的解决方法吗？

**Comment by JiaquanYe** [comment]
> 您好，按照Install.md安装了mmdetection、mmcv-full、mmocr，
> 但是运行 sh ./table_recognition/expr/table_recognition_dist_train.sh 报错：
> keyError:'TABLEMASTER is not in the {registry.name} registry'，
> 请问有什么建议的解决方法吗？

Please check mmocr installation. It seems not install mmocr successfully.

**Comment by myh12138** [comment]
> 您好，按照Install.md安装了mmdetection、mmcv-full、mmocr，
> 但是运行 sh ./table_recognition/expr/table_recognition_dist_train.sh 报错：
> keyError:'TABLEMASTER is not in the {registry.name} registry'，
> 请问有什么建议的解决方法吗？

test_anno_file1 = '/data_0/yejiaquan/data/TableRecognization/mergeStructLabelsAddEmptyEsb_val/'
can you share how to make mergeStructLabelsAddEmptyEsb_val,thanks

**Comment by JiaquanYe** [comment]
> > 您好，按照Install.md安装了mmdetection、mmcv-full、mmocr，
> > 但是运行 sh ./table_recognition/expr/table_recognition_dist_train.sh 报错：
> > keyError:'TABLEMASTER is not in the {registry.name} registry'，
> > 请问有什么建议的解决方法吗？
> 
> test_anno_file1 = '/data_0/yejiaquan/data/TableRecognization/mergeStructLabelsAddEmptyEsb_val/'
> can you share how to make mergeStructLabelsAddEmptyEsb_val,thanks

It is same to the way preparing training data. You can change the 'split' to 'val' in [this code line](https://github.com/JiaquanYe/TableMASTER-mmocr/blob/6c69e29da51c32be118828735ce0ed188a8b647e/table_recognition/data_preprocess.py#L417)

**Comment by tangjiashan7** [comment]
我也遇到这个问题了  感觉不是mmocr的问题

**Comment by JiaquanYe** [comment]
Docker environment has been released. Maybe you can try it. 
Get docker images by 'docker pull jiaquanye/tablemaster_mmocr:v1'

**Comment by zjw-gh** [comment]
请问解决了吗？
